---
title: "STA2453H1Y - Data Science Methods, Collaboration, and Communication"
subtitle: "Syllabus"
output:
  html_document:
    theme: cosmo
    highlight: textmate
    toc: true
    toc_float: true
---


# Instructor

[Nikola Počuča](https://ca.linkedin.com/in/nik-po%C4%8Du%C4%8Da-1b46a2173)

# Course Description

Students will gain experience with the data science process including: 

- Data collection
- Data wrangling
- Program ([Python](https://www.python.org)/[R](https://cran.r-project.org))
- Data exploration
- Data vizualization
- Modelling
- Communication
- Reproducibility

Students will learn about these topics by working on case studies based on problems that data scientists face in industry and academic research. Many of the cases will involve data collected by an organization (e.g., organization or scientist), using published data, or scraping web pages.  All projects will involve some type of collaboration or communication. Students are expected to be familiar with the application of basic statistical methods used for inference (e.g., general linear models), prediction (e.g., linear and logistic regression), and are comfortable with basic data analysis using a programming language such as R or Python.  Students will be expected to adopt a reproducible research workflow using tools such as [Github](https://github.com), and [RMarkdown](https://rmarkdown.rstudio.com), or [Jupyter](https://jupyter.org). 

Class time will be a mixture of informal lectures, class discussions, and student presentations.

# Evaluation

All work will be graded on a scale from 1 to 4 (sometimes with pluses and minuses) where:


------------------------------------------------------------------------
Grade value   Description
-----------   ---------------------------------------------------------
1             Work does not meet expectations.

2             Work meets expectations minimally, possibly missing some.

3             Good work; meets all or most expectations.

4             Excellent work; exceeds expectations.
------------------------------------------------------------------------


Grades will almost always be 2 or 3 (1’s and 4’s are rare). Generally speaking, a 2 is a B, a 3 is an A, and a 4 is an A+.

# Breakdown 

Lab 1: 10%
Lab 2: 10% 
Lab 3: 10%
Project 1: 20%
Project 2: 20%
Project 3: 20%
Participation 10%

# Course Schedule

This is a half-credit that meets in both the fall and winter terms.  Class meeting will occur approximately bi-weekly. Location is 17th floor of The OPG building, class
UY 17198. 


| Date  | Description |
| ----------- | ----------- |
| September 8th | Course officially begins. |
| September 13th   | First class, Introductions, Python/R setups, Data Analysis |
| September 27th | In Class Lab 1, Multiple Linear Regression | 
| October 11th | Generalized Linear Models | 
| October 25th | Mixture Models and Data Heterogeneity | 
| November 8th | Reading Week | 
| November 22nd | In Class Lab 2, Data Quality, Ethics, and Missing/Asymmetric Data Imputation |
| December 6th | In Class Lab 3, Nonparametrics, and a discussion of Hayashian Data Science |
| Winter Break | |





## Required Readings

- [ISLR](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf)

- [Python for Data Analysis 2nd/3rd Edition](https://wesmckinney.com/book/)

Other readings may be assigned during the course.


## Slides and Materials 
- Week 1: [Slides](https://docs.google.com/presentation/d/15RgjoU7fKz_AFcCyW8qXxrRwj04FeZji-K0mWla_gBQ/edit?usp=sharing) and [Code](https://colab.research.google.com/drive/1L1Kx8qoHCY3yjuYg2tE4W61xu79xG7lJ?usp=sharing)

---

### Lab 1 Study Guide 

The lab will consist of the following topics, please brush up on them since this is a timed evaluation, and you will only have an hour. 

---

### Part 1 Data Cleaning 

Textbook study guide: Python for Data Analysis Chapters 4, 6, and 7. This part of the lab will require you to load a dataset from a link, 
clean the data in a certain way using some constraints, and generate two distinct pandas dataframes. 

---

### Part 2 Numpy Calculation

Textbook study guide: Python for Data Analysis Chapters 4. This part of the lab will require you to take 2 columns from 2 different datasets and 
calculate a metric using both columns. Essentially this question is somewhat of a map-reduce problem. Revise your broadcasting, working with `np.array`, for-loops, and generally numpy skills. 

### Part 3 Distributional Characteristic Statistics

This part can be tackled 1 of 2 ways for full marks. You will be marked qualitatively, so the more analysis/justification you write the better off you will be. 
The last end conclusion will separate you from a 3 to a 4. There is a way to do this question without simulations. 

- Please review all week-1 lecture notes found here: [Notes](https://colab.research.google.com/drive/1L1Kx8qoHCY3yjuYg2tE4W61xu79xG7lJ?usp=sharing) 
- Absolutely essential reading: 13.5.1 A Re-Sampling Approach to the p-Value [ISLR](https://hastie.su.domains/ISLR2/ISLRv2_website.pdf), Algorithm 13.3, we covered only half of this algorithm in class, with the remaining part would be to just compare your p-value to the distributions of re-sampled p-values, or calculate equation (13.12).

Useful functions for this question, `np.random.choice`. Try coding this algorithm up yourself! with different types of distributions, Gaussian, Generalized Hyperbolic, or Lognormal distributions. You can send me emails with code examples. 




